<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Acme.Pki.Shared.Utils</RootNamespace>
  <AssemblyName>Acme.Pki.Shared.Utils</AssemblyName>
</PropertyGroup>

</Project>
